backend:
  name: git-gateway #git-gateway #test-repo
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Preview Image', name: 'cover', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Categories', name: 'category', widget: 'select', multiple: true, options: ["workout", "travel", "code", "philosophy"] }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'parts'
    label: 'Parts'
    folder: 'content/parts'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }