backend:
  name: github #github #test-repo
  branch: master
  repo: continentalecoservice/continental-eco.ru # Path to your GitHub repository

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'sliders'
    label: 'Sliders'
    folder: 'content/sliders'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Preview Image', name: 'cover', widget: 'image' }
      - { label: 'Icon', name: 'icon', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

      - label: "ContentList"
        name: "contentList"
        collapsed: false
        widget: "list"
        fields:
          - { label: 'Item', name: 'item', widget: 'string', default: "Обработка поверхностей дезинфицирующим раствором" }

  - name: 'pageInfo'
    label: 'PageInfo'
    folder: 'content/pageInfo'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Support Phone', name: 'supportPhone', widget: 'text', default: '+7 (495) 227-56-56' }
      - { label: 'Email', name: 'email', widget: 'text', default: 'ecoservice@gmail.com' }
      - { label: 'Address', name: 'address', widget: 'text', default: 'Москва, ул. Нижегородская, 29-33' }
      - { label: 'WorkTime', name: 'workTime', widget: 'text', default: '9:00 - 17:00' }
      - { label: 'General Phone', name: 'generalPhone', widget: 'text', default: '+7495 755 69 83' }
      - { label: 'Facebook', name: 'facebook', widget: 'text', default: 'https://facebook.com/' }
      - { label: 'Instagram', name: 'instagram', widget: 'text', default: 'https://instagram.com/' }
      - { label: 'Whatsapp', name: 'whatsapp', widget: 'text', default: 'https://whatsapp.com/' }
      - { label: 'Viber', name: 'viber', widget: 'text', default: 'https://viber.com/' }
      - { label: 'Telegram', name: 'telegram', widget: 'text', default: 'https://telegram.com/' }