backend:
  name: github #github #test-repo
  branch: master
  repo: continentalecoservice/continental-eco.ru # Path to your GitHub repository

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'parts'
    label: 'Parts'
    folder: 'content/parts'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'sliders'
    label: 'Sliders'
    folder: 'content/sliders'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Preview Image', name: 'cover', widget: 'image' }